### ISSUE TITLE
libprotobuf.so.20: cannot open shared object file with Protobuf 0.8

### ISSUE THREAD

**Issue by tanguycdls** [conda-forge/onnx-feedstock#29]
Hi i noticed the following behavior:
Issue:

<br/>
I'm using the docker image of miniconda from continuumio:latest version (4.7.10) fresh install. 

<details>

_libgcc_mutex             0.1                        main  
asn1crypto                0.24.0                   py27_0  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py27_1    conda-forge
cffi                      1.12.3           py27h2e261b9_0  
chardet                   3.0.4                    py27_1  
conda                     4.7.11                   py27_0    conda-forge
conda-package-handling    1.3.11                   py27_0  
cryptography              2.7              py27h1ba5d50_0  
enum34                    1.1.6                    py27_1  
futures                   3.3.0                    py27_0  
idna                      2.8                      py27_0  
ipaddress                 1.0.22                   py27_0  
libarchive                3.3.3                h5d8350f_5  
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
liblapack                 3.8.0               12_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_1    conda-forge
libprotobuf               3.8.0                h8b12597_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libxml2                   2.9.9                hea5a465_1  
lz4-c                     1.8.1.2              h14c3975_0  
lzo                       2.10                 h49e0be7_2  
ncurses                   6.1                  he6710b0_1  
numpy                     1.16.4           py27h95a1406_0    conda-forge
onnx                      1.5.0            py27he1b5a44_2    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pip                       19.1.1                   py27_0  
protobuf                  3.8.0            py27he6710b0_0  
pycosat                   0.6.3            py27h14c3975_0  
pycparser                 2.19                     py27_0  
pyopenssl                 19.0.0                   py27_0  
pysocks                   1.7.0                    py27_0  
python                    2.7.16               h9bab390_0  
python-libarchive-c       2.8                     py27_11  
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   py27_0  
ruamel_yaml               0.15.46          py27h14c3975_0  
setuptools                41.0.1                   py27_0  
six                       1.12.0                   py27_0  
sqlite                    3.29.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
tqdm                      4.32.1                     py_0  
typing                    3.7.4.1                  py27_0    conda-forge
urllib3                   1.24.2                   py27_0  
wheel                     0.33.4                   py27_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
    active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.7.11
    conda-build version : not installed
         python version : 2.7.16.final.0
       virtual packages : 
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/2.7.16 Linux/4.9.125-linuxkit debian/10 glibc/2.28
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</details>

- when installing through conda install onnx installs protobuf 3.9 and everything works. 
- If you have a previous version of protobuf (if you have tensorflow for example) and the version is 3.8 it breaks at import with the following message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python2.7/site-packages/onnx/__init__.py", line 14, in <module>
    import onnx.helper  # noqa
  File "/opt/conda/lib/python2.7/site-packages/onnx/helper.py", line 13, in <module>
    import onnx.defs as defs
  File "/opt/conda/lib/python2.7/site-packages/onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: libprotobuf.so.20: cannot open shared object file: No such file or directory
```
Force install to protobuf 3.9 works. 

EDIT:
 Actually I still have an issue: Tensorflow and Pyarrow from Conda Forge are build in Protobuf 3.8 and so I cannot install all of them in the same machine: how could I find a version of ONNX that works on 3.8. 
Thanks

**Comment by Cloudmersive** [comment]
It's amazing that ONNX is currently DOA and nobody is fixing it for months coming up on years

**Comment by marcelotrevisani** [comment]
We can rebuild it with protobuf 3.8 in a separated branch, I am fixing some stuffs here
https://github.com/conda-forge/onnx-feedstock/pull/37
I will wait for it first


> It's amazing that ONNX is currently DOA and nobody is fixing it for months coming up on years

``conda-forge`` is a community where people give their free time to try to improve packaging and all that stuff, you are more than welcome to fix the problem and open a PR as well  :)

**Comment by ocefpaf** [comment]
> It's amazing that ONNX is currently DOA and nobody is fixing it for months coming up on years

@Cloudmersive conda-forge is a community of volunteers. Please join us and help fix this! PRs are welcome!

**Comment by marcelotrevisani** [comment]
Closing this in favor of https://github.com/conda-forge/onnx-feedstock/pull/39
