### ISSUE TITLE
Updating Windows package

### ISSUE THREAD

**Issue by kevinch-nv** [conda-forge/onnx-feedstock#33]
Opening this issue because the process for updating the Windows packages are not clear. The `v1.6.0` changes were up streamed to https://anaconda.org/conda-forge/onnx but the Windows packages are still showing version `v1.1.1`.

What steps are necessary to update the Windows versions?

**Comment by marcelotrevisani** [comment]
Closing in favour of https://github.com/conda-forge/onnx-feedstock/pull/47
