### ISSUE TITLE
A new maintainer proposal

### ISSUE THREAD

**Issue by p-wysocki** [conda-forge/onnx-feedstock#86]
### Comment:

Hi! 

I want to propose a new maintainer for `onnx-feedstock` - https://github.com/ilya-lavrenov. There are some PRs that our product (OpenVINO) depends on and we would love to help with maintenance in order to get them merged quicker.

I talked to ONNX SIG Operators Team and they were supportive of this proposition.

cc @marcelotrevisani @xhochy

**Comment by xhochy** [comment]
Maintainer access is given based on merit here. If @ilya-lavrenov wants to be a maintainer, they should contribute here, and then we can add them as a maintainer. `ONNX SIG Operators Team` is totally unrelated to this feedstock and doesn't over anything here, so their approval is not needed.
